# Generated by Django 3.2.13 on 2022-05-31 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('TransactionCreated', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(choices=[(-1, -1), (100, 100), (0, 0)], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_profile', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('API_KEY', models.CharField(blank=True, default='', max_length=200)),
                ('API_SECRET', models.CharField(blank=True, default='', max_length=1000)),
                ('TransactionID', models.CharField(blank=True, default='', max_length=200)),
                ('wallet', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('paid_month', models.BooleanField(default=False)),
                ('profit_value', models.CharField(blank=True, default='', max_length=200)),
                ('profit_flag', models.BooleanField(default=False)),
                ('run_flag', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=12)),
                ('forgot_password_token', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_activated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('settings_flag', models.BooleanField(default=False)),
                ('run_profile_button_flag', models.BooleanField(default=False)),
                ('wallet_activate_flag', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(choices=[(-1, -1), (100, 100), (0, 0)], default=0)),
                ('referral_level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('referral_commission', models.IntegerField(choices=[(5, 5), (7, 7), (10, 10), (14, 14), (19, 19), (25, 25)], default=5)),
                ('referral_earned', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
