# Generated by Django 3.2.13 on 2022-05-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0002_alter_profile_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='API_SECRET',
            field=models.BinaryField(blank=True),
        ),
    ]
