# Generated by Django 3.2.13 on 2022-06-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0005_remove_boterrors_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boterrors',
            name='Error',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
