# Generated by Django 3.2.13 on 2022-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0006_alter_boterrors_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transaction_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
