# Generated by Django 3.2.13 on 2022-06-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0007_profile_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='transaction_type',
        ),
    ]
