# Generated by Django 3.2.13 on 2022-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0008_remove_profile_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
