# Generated by Django 3.2.13 on 2022-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0009_alter_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_months',
            field=models.IntegerField(default=0),
        ),
    ]
