# Generated by Django 3.2.13 on 2022-06-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0011_alter_profile_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='risk_profile',
            field=models.CharField(choices=[('vlow', 'vLow'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('vhigh', 'vHigh')], default='medium', max_length=12),
        ),
    ]
