# Generated by Django 3.2.13 on 2022-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0013_transactionhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer')], default='deposit', max_length=12),
        ),
    ]
