# Generated by Django 3.2.13 on 2022-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseapp', '0014_alter_transactionhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings_flag',
            field=models.BooleanField(default=True),
        ),
    ]
